# Site settings
title: Ayush Kumar
email: ayush@ayushk.cf
url: https://iaks.cf
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Ayush Kumar

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Ayushkumaravk
  - title: facebook
    url: https://facebook.com/Ayushkumaravk
  - title: stack-overflow
    url: http://stackoverflow.com/users/Ayushkumaravk
  - title: bitbucket
    url: http://bitbucket.org/Ayushkumaravk
  - title: github
    url: https://github.com/Ayushkumaravk
  - title: Medium
    url: https://medium.com/@Ayushkumaravk
  - title: Tradingview
    url: https://in.tradingview.com/u/ayushkumaravk
# Build settings
markdown: kramdown
permalink: pretty
